#ifndef IDS_OF_CONTROLS_H
#define IDS_OF_CONTROLS_H

enum IDs
{
    ID_LOAD_IMG = 2,
    ID_SAVE_IMG,
    ID_ZOOM_IN,
    ID_ZOOM_OUT,
    ID_ROTATE_SCALE,
    ID_OPEN_AZSM,
    ID_RUN_DETECTORATOR,
    ID_APPLY_ROTATE_SCALE,
    ID_USE_MULT_PROC,
    ID_GBS_SPIN,
    ID_OPEN_OPTIONS,
};

#endif
