#ifndef IDS_OF_CONTROLS_H
#define IDS_OF_CONTROLS_H

enum IDs
{
    ID_LOAD_IMG = 2,
    ID_SAVE_IMG,
    ID_ZOOM_IN,
    ID_ZOOM_OUT,
    ID_ROTATE_SCALE,
    ID_OPEN_AZSM,
    ID_RUN_DETECTORATOR,
    ID_APPLY_ROTATE_SCALE,
    ID_USE_MULT_PROC,
    ID_AZSM_GBS_SPIN,
    ID_AZSMMP_BTV_MIN_SPIN,
    ID_AZSMMP_ICP_MIN_SPIN,
    ID_AZSMMP_GC_MIN_SPIN,
    ID_AZSMMP_GBS_MIN_SPIN,
    ID_AZSMMP_GBS_MAX_SPIN,
    ID_AZSMMP_GBS_STEP_SPIN,
    ID_OPEN_OPTIONS,
    ID_AZSM_MP,
    ID_START_MP,
    ID_SRC_DIR_PICKER,
    ID_DST_DIR_PICKER,
};

#endif
